services:
    php:
        build:
            context: .
        container_name: frankenphp
        restart: always
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
            - "443:443/udp" # HTTP/3
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        tty: true

volumes:
    caddy_data:
    caddy_config:
